language: java

jdk:
  - openjdk11

os:
  - linux
stages:
  - compile
  - name: deploy
    if: branch = master


jobs:
  include:
    - stage: compile
      script: ./gradlew clean assemble
    - stage: deploy
      script: ./gradlew bintrayUpload