language: android
dist: trusty
android:
  components:
    - build-tools-28.0.3
    - android-29

stages:
  - compile
  - name: deploy
    if: branch = master


jobs:
  include:
    - stage: compile
      script: ./gradlew clean library:assemble
    - stage: deploy
      script: ./gradlew library:bintrayUpload
